version: '3.9'
services:
  backend:
    image: hello-world-spring-boot
    ports:
      - '8080:8080'
    networks:
      - hello-world-network
  frontend:
    image: hello-world-react
    ports:
      - '8002:80'
    networks:
      - hello-world-network
networks:
  hello-world-network:
    external: true
